qla2xxx-32gbit: Remove unnecessary NULL check
The list iterator can't be NULL so this check is not required.  Removing
the check silences a Smatch warning about inconsistent NULL checking.

    drivers/scsi/qla2xxx/qla_dfs.c:371 qla_dfs_tgt_counters_show()
    error: we previously assumed 'fcport' could be null (see line 372)

Link: https://lore.kernel.org/r/YAkaaSrhn1mFqyHy@mwanda
Acked-by: Saurav Kashyap <skashyap@marvell.com>
Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

[ commit c750a9c9c59a85843d447910a27da21c5bcf600a upstream ]


git-svn-id: http://svn.code.sf.net/p/scst/svn/trunk@9356 d57e44dd-8a1f-0410-8b47-8ef2f437770f