qla2x00t-32gbit: Fix compilation issue in PPC systems
Fix compile time errors reported on PPC systems,

qla_gbl.h:991:20: error: inlining failed in call to always_inline
     qla_nvme_abort_set_option: function body not available

Link: https://lore.kernel.org/r/20201202132312.19966-7-njavali@marvell.com
Signed-off-by: Arun Easi <aeasi@marvell.com>
Signed-off-by: Nilesh Javali <njavali@marvell.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>

See also upstream commit aceba54ba0f998ed6bec88faaf94e7458f753399.


git-svn-id: http://svn.code.sf.net/p/scst/svn/trunk@9295 d57e44dd-8a1f-0410-8b47-8ef2f437770f