github: Ignore errors when building SCST for Coverity
The GitHub virtual environment provides Ubuntu with a kernel that doesn't
support FCoE, causing the build to fail:

ERROR: modpost: "fc_seq_release" [/root/gleb/SCST/scst/fcst/fcst.ko] undefined!
ERROR: modpost: "fc_fc4_register_provider" [/root/gleb/SCST/scst/fcst/fcst.ko] undefined!
ERROR: modpost: "fc_lport_iterate" [/root/gleb/SCST/scst/fcst/fcst.ko] undefined!
ERROR: modpost: "fc_seq_els_rsp_send" [/root/gleb/SCST/scst/fcst/fcst.ko] undefined!
ERROR: modpost: "fc_seq_assign" [/root/gleb/SCST/scst/fcst/fcst.ko] undefined!
ERROR: modpost: "_fc_frame_alloc" [/root/gleb/SCST/scst/fcst/fcst.ko] undefined!
ERROR: modpost: "fc_fill_reply_hdr" [/root/gleb/SCST/scst/fcst/fcst.ko] undefined!
ERROR: modpost: "fc_exch_done" [/root/gleb/SCST/scst/fcst/fcst.ko] undefined!
ERROR: modpost: "fc_fc4_deregister_provider" [/root/gleb/SCST/scst/fcst/fcst.ko] undefined!
ERROR: modpost: "fc_frame_alloc_fill" [/root/gleb/SCST/scst/fcst/fcst.ko] undefined!
WARNING: modpost: suppressed 4 unresolved symbol warnings because there were too many)

Ignore these errors and continue building SCST to get all the information
for analysis.